# Generated by Django 2.1.3 on 2018-11-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comiccomment',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='comiccomment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comic',
            name='comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ComicComment',
        ),
    ]
